/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.TO.CompanyInfoTO;
import model.TO.ProductTypeTO;
import model.dao.CompanyinfoDAO;
import operations.validations;

/**
 *
 * @author user
 */
public class addcompanyinfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form 
     */
    public addcompanyinfo() {
        initComponents();
    }
     public addcompanyinfo(CompanyInfoTO ci){
          this();
          if(ci!=null){
              jtfcompanyid.setText(ci.getCompanyid());
              jtfcompanyname.setText(ci.getCompanyname());
              btnaddcompanyinfo.setText("update record");
              setTitle("IMS::update companyinfo");
              jtfcompanyid.setEditable(false);
          }
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfcompanyname = new javax.swing.JTextField();
        jtfcompanyid = new javax.swing.JTextField();
        btnaddcompanyinfo = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("IMS::ADD COMPANY INFO");

        jLabel1.setFont(new java.awt.Font("KodchiangUPC", 1, 29)); // NOI18N
        jLabel1.setText("Enter Company ID:");

        jLabel2.setFont(new java.awt.Font("KodchiangUPC", 1, 29)); // NOI18N
        jLabel2.setText("Enter Company Name:");

        btnaddcompanyinfo.setFont(new java.awt.Font("KodchiangUPC", 1, 36)); // NOI18N
        btnaddcompanyinfo.setText("Add Company Info");
        btnaddcompanyinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcompanyinfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcompanyid, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaddcompanyinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfcompanyid, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfcompanyname, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(58, 58, 58)
                .addComponent(btnaddcompanyinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddcompanyinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcompanyinfoActionPerformed
       
        String companyid=jtfcompanyid.getText().trim();
       String companyname=jtfcompanyname.getText().trim();
       String message="";
      ;
       if(validations.isEmpty(companyid)){
           message="please enter companyid";
       }else if(validations.isEmpty(companyname)){
            message="please enter company details";
       }
       else {
           CompanyInfoTO ci=new CompanyInfoTO();
           ci.setCompanyid(companyid);
           ci.setCompanyname(companyname);
        
          CompanyinfoDAO action=new CompanyinfoDAO();
           
        if(btnaddcompanyinfo.getText().contains("Add"))
       {
                       if(action.insertrecord(ci)){
               message="New record are added";
                 //for automatic refresh
               JInternalFrame[] jif= getDesktopPane().getAllFrames();
               if(jif!=null)
                       {
                           for(JInternalFrame jf:jif)
                                   {
                                       if(jf instanceof viewcompanyinfo)
                                       {
                                          viewcompanyinfo vpt=(viewcompanyinfo)jf;
                                          vpt.bindcoursetable();
                                          break;
                                       }
                                       
                                   }
                       }
           }else {
               message=action.geterrormessage();
           }}else if (btnaddcompanyinfo.getText().contains("update")){
              ci.setCompanyid(companyid);
              ci.setCompanyname(companyname);
               if(action.updaterecord(ci)){
                  message="company info is updated in system";
                   }else{
                   message=action.geterrormessage();
               }
               viewcompanyinfo vpt=new viewcompanyinfo();
               vpt.setVisible(true);
               getDesktopPane().add(vpt);
               try{
                   vpt.setSelected(true);
               }catch(PropertyVetoException ex){
                   
               }
               
                       
       }
       }
       

           
        JOptionPane.showMessageDialog(this, message);
    
    

    }//GEN-LAST:event_btnaddcompanyinfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcompanyinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtfcompanyid;
    private javax.swing.JTextField jtfcompanyname;
    // End of variables declaration//GEN-END:variables
}