/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.beans.PropertyVetoException;
import java.sql.Timestamp;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.TO.ProductTypeTO;
import model.TO.logininfoTO;
import model.dao.LogininfoDAO;
import model.dao.ProductTypeDAO;
import operations.validations;

/**
 *
 * @author user
 */
public class addlogininfo extends javax.swing.JInternalFrame {

  
    public addlogininfo() {
        initComponents();
         jcbrolename.removeAllItems();
        jcbrolename.addItem("select role name");
        jcbrolename.addItem("admin");
         jcbrolename.addItem("user");
       
    }
     public addlogininfo(logininfoTO pt) {
        this();

        if (pt != null) {

            jtfusername.setText(String.valueOf(pt.getUsername()));
            jpfpassword.setText(pt.getPassword());
            
            btnaddlogininfo.setText("update record");
            setTitle("IMS::update logininfo");
            for (int i = 1; i < jcbrolename.getItemCount(); i++) {
               String cit = jcbrolename.getItemAt(i);
                if (String.valueOf(cit).equals(String.valueOf(pt.getRolename()))) {
                    jcbrolename.setSelectedIndex(i);
                    break;
                }

            }
            

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfusername = new javax.swing.JTextField();
        jpfpassword = new javax.swing.JPasswordField();
        btnaddlogininfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcbrolename = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setTitle("IMS::Login Screen");

        jLabel1.setFont(new java.awt.Font("KodchiangUPC", 1, 34)); // NOI18N
        jLabel1.setText("Password:");

        jLabel2.setFont(new java.awt.Font("KodchiangUPC", 1, 34)); // NOI18N
        jLabel2.setText("User/admin Name:");

        btnaddlogininfo.setBackground(new java.awt.Color(255, 255, 102));
        btnaddlogininfo.setFont(new java.awt.Font("KodchiangUPC", 1, 30)); // NOI18N
        btnaddlogininfo.setText("Add Login Info");
        btnaddlogininfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddlogininfoActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminui/App-login-manager-icon.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("KodchiangUPC", 1, 34)); // NOI18N
        jLabel4.setText("Role Name:");

        jcbrolename.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jtfusername))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnaddlogininfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                            .addComponent(jpfpassword)
                            .addComponent(jcbrolename, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfusername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpfpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbrolename, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaddlogininfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddlogininfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddlogininfoActionPerformed
         String username=jtfusername.getText().trim();
        String password = new String(jpfpassword.getPassword());
        String rolename=jcbrolename.getSelectedItem().toString();
        
       String message=" ";
        boolean allvalid = true;
      
       
       
        if (validations.isEmpty(username)) {
            message = "Enter user name";
            allvalid = false;
        }
         if (validations.isEmpty(password)) {
            message = "Enter password name";
            allvalid = false;
        }
        if (jcbrolename.getSelectedIndex() == 0) {
            message = "Choose rolename";
            allvalid = false;
        }
         
       
        if (allvalid) {
           logininfoTO pt=new logininfoTO();
            
           
             
          pt.setUsername(username);
           pt.setPassword(password);
            System.out.println("heelo error");
           pt.setRolename(rolename);
         
           LogininfoDAO action=new LogininfoDAO();
            if(btnaddlogininfo.getText().contains("Add"))
       {
           if(action.insertrecord(pt)){
               message="New record are added";
               //for automatic refresh
               JInternalFrame[] jif= getDesktopPane().getAllFrames();
               if(jif!=null)
                       {
                           for(JInternalFrame jf:jif)
                                   {
                                       if(jf instanceof viewproducttype)
                                       {
                                          viewproducttype vpt=(viewproducttype)jf;
                                          vpt.bindcoursetable();
                                          break;
                                       }
                                       
                                   }
                       }
               
           }else{
               message=action.geterrormessage();
           }}else if(btnaddlogininfo.getText().contains("update")){
              pt.setUsername(username);
           pt.setPassword(password);
           pt.setRolename(rolename);
           
               if(action.updaterecord(pt)){
                  message="login info is updated in system";
                   }else{
                   message=action.geterrormessage();
               }
               viewlogininfo vpt=new viewlogininfo();
               vpt.setVisible(true);
               getDesktopPane().add(vpt);
               try{
                   vpt.setSelected(true);
               }catch(PropertyVetoException ex){
                   
               }
               
                       
       }
            
       
    }                                                 
 JOptionPane.showMessageDialog(this, message);
    
    }//GEN-LAST:event_btnaddlogininfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddlogininfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jcbrolename;
    private javax.swing.JPasswordField jpfpassword;
    private javax.swing.JTextField jtfusername;
    // End of variables declaration//GEN-END:variables
}
