/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.TO.ProductTypeTO;
import model.dao.ProductTypeDAO;
import operations.validations;

/**
 *
 * @author user
 */
public class addproducttype extends javax.swing.JInternalFrame {

    public addproducttype() {
        initComponents();
      
    }
      public addproducttype(ProductTypeTO pt){
          this();
          if(pt!=null){
              jtftypeid.setText(pt.getTypeid());
              jtftypename.setText(pt.getTypename());
              btnaddproducttype.setText("update record");
              setTitle("IMS::update producttype");
              jtftypeid.setEditable(false);
          }
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnaddproducttype = new javax.swing.JButton();
        jtftypename = new javax.swing.JTextField();
        jtftypeid = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("IMS::ADDPRODUCTTYPE");

        jLabel1.setFont(new java.awt.Font("KodchiangUPC", 1, 29)); // NOI18N
        jLabel1.setText("Enter Type Name:");

        jLabel2.setFont(new java.awt.Font("KodchiangUPC", 1, 29)); // NOI18N
        jLabel2.setText("Enter Type ID:");

        btnaddproducttype.setFont(new java.awt.Font("KodchiangUPC", 1, 36)); // NOI18N
        btnaddproducttype.setText("Add product Info");
        btnaddproducttype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddproducttypeActionPerformed(evt);
            }
        });

        jtftypeid.setFont(new java.awt.Font("KodchiangUPC", 1, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtftypeid, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftypename, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(252, 252, 252))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnaddproducttype, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(621, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jtftypeid, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftypename, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnaddproducttype, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(241, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddproducttypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddproducttypeActionPerformed
       
  
       String typeid=jtftypeid.getText().trim();
       String typename=jtftypename.getText().trim();
       String message=" ";
      
       if(validations.isEmpty(typeid)){
           message="please enter typeid";
       }else if(validations.isEmpty(typename)){
           message="please enter typename";
       }
       else{
           ProductTypeTO pt=new ProductTypeTO();
          pt.setTypeid(typeid);
           pt.setTypename(typename);
           ProductTypeDAO action=new ProductTypeDAO();
            if(btnaddproducttype.getText().contains("Add"))
       {
           if(action.insertrecord(pt)){
               message="New record are added";
               //for automatic refresh
               JInternalFrame[] jif= getDesktopPane().getAllFrames();
               if(jif!=null)
                       {
                           for(JInternalFrame jf:jif)
                                   {
                                       if(jf instanceof viewproducttype)
                                       {
                                          viewproducttype vpt=(viewproducttype)jf;
                                          vpt.bindcoursetable();
                                          break;
                                       }
                                       
                                   }
                       }
               
           }else{
               message=action.geterrormessage();
           }}else if(btnaddproducttype.getText().contains("update")){
              pt.setTypeid(typeid);
              pt.setTypename(typename);
               if(action.updaterecord(pt)){
                  message="product type is updated in system";
                   }else{
                   message=action.geterrormessage();
               }
               viewproducttype vpt=new viewproducttype();
               vpt.setVisible(true);
               getDesktopPane().add(vpt);
               try{
                   vpt.setSelected(true);
               }catch(PropertyVetoException ex){
                   
               }
               
                       
       }
            
       
    }//GEN-LAST:event_btnaddproducttypeActionPerformed
 //JOptionPane.showMessageDialog(this, message);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddproducttype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jtftypeid;
    private javax.swing.JTextField jtftypename;
    // End of variables declaration//GEN-END:variables
}
