/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminui;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.TO.ProductTypeTO;
import model.dao.ProductTypeDAO;

/**
 *
 * @author user
 */
public class viewproducttype extends javax.swing.JInternalFrame {

    List<ProductTypeTO> products;
    private JPopupMenu popupmenu;
    int row;
    public viewproducttype() {
        initComponents();
        bindcoursetable();
        popupmenu=new JPopupMenu();
        JMenuItem jdeleteitem=new JMenuItem("delete this record");
      
        jdeleteitem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              deleterecord();
            }
        });
        popupmenu.add(jdeleteitem);
        JMenuItem jupdateitem=new JMenuItem("update this record");
         jupdateitem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
              updaterecord();
            }
        });
        popupmenu.add(jupdateitem);
        row=-1;
        
    }
    private void updaterecord(){
         if(row!=-1 && products!=null && row<products.size()){
             ProductTypeTO pt=products.get(row);
             addproducttype apt=new addproducttype(pt);
             apt.setVisible(true);
             getDesktopPane().add(apt);
             try{
                 apt.setSelected(true);
                 
             }catch(PropertyVetoException ex){
                 
                 
             }
              
             dispose();
           
             
         }
        
    }
    private void deleterecord(){
        if(row!=-1 && products!=null && row<products.size()){
            int result=JOptionPane.showConfirmDialog(this, "are you sure to delete item","message from system",JOptionPane.YES_NO_OPTION);
            if (result==JOptionPane.YES_OPTION){
            ProductTypeTO pt=products.get(row);
            String message="";
            ProductTypeDAO action=new ProductTypeDAO();
            if(action.deleterecord(pt.getTypeid())){
                message="record is deleted";
                bindcoursetable();
                
            }else{
                message=action.geterrormessage();
            }
            JOptionPane.showMessageDialog(this, message);
            }
        }
        
        row=-1;
    }
    public void bindcoursetable(){
    products=new ProductTypeDAO().getAllRecord();
    String[] colnames={"typeid","typename"};
    Object[][] records=null;
    if(products.size()>0 && products!=null)
    {
        records=new Object[products.size()][colnames.length];
        int i=0;
        for(ProductTypeTO pit:products)
        {
            records[i]=new Object[]{pit.getTypeid(),pit.getTypename()};
            i++;
        }
        
    }else{
        records=new Object[1][colnames.length];
        records[0]=new Object[]{"no records","no records"};
    }
         DefaultTableModel dtm=new DefaultTableModel(records, colnames){
         

        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
            
        
                 
       
      }
      
               
      };
         tableproductype.setAutoCreateRowSorter(true);
          tableproductype.getTableHeader().setReorderingAllowed(false);
                 tableproductype.setModel(dtm);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableproductype = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("IMS::View product type");

        tableproductype.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableproductype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableproductypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableproductype);

        jButton1.setFont(new java.awt.Font("KodchiangUPC", 1, 36)); // NOI18N
        jButton1.setText("Refresh Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       bindcoursetable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableproductypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableproductypeMouseClicked
      if(evt.getButton()==MouseEvent.BUTTON3){
          int rowpos=tableproductype.rowAtPoint(evt.getPoint());
          tableproductype.getSelectionModel().setSelectionInterval(rowpos,rowpos);
          popupmenu.show(tableproductype, getX(), getY());
          row=tableproductype.getSelectedRow();
          
      }
    }//GEN-LAST:event_tableproductypeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableproductype;
    // End of variables declaration//GEN-END:variables
}
